[pytest]
log_format = %(asctime)s | %(message)s
log_date_format = %d-%m-%Y %H:%M:%S

addopts = -s -v --show-capture=no --client=lirunex --account=demo --debuglog
python_functions =
    test_*

python_files =
    test*

markers =
    positive
    negative
    integration