

url:
  lirunex: https://lirunex-global-mb.webtrader-sit.s20ip12.com
  transactCloud: https://transactcloudmt5-mb.webtrader-sit.s20ip12.com

# Credential
# ----------
user_id: 569205553
email: mt5_automation58@mailinator.com
password: QXV0b0AxMjM0NQ==
#password: Autotest@12345
#password: Giabao123



